server:
  port: 8091
spring:
  application:
    name: micro-stock-subscribe
  datasource:
    url: jdbc:h2:mem:stock-subscribe;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: password
    driverClassName: org.h2.Driver
  sql:
    init:
      platform: h2
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
    enabled: true
    path: /console
    settings:
    trace: false
    web-allow-others: false
  thymeleaf:
    cache: off
    encoding: UTF-8


